### ISSUE TITLE
Train运行错误的问题

### ISSUE THREAD

**Issue by Alex76budy** [bubbliiiing/mobilenet-yolov4-pytorch#42]
老师好，我在运行自己数据集时出现了以下错误，每次都是运行10个epoch后，calculate map后出现问题，
Traceback (most recent call last):
  File "D:\python\pycharm\documentes\project\deep-learning-for-image-processing-master\object\mobilenet-yolov4-pytorch-main\utils\callbacks.py", line 208, in on_epoch_end
    temp_map = get_coco_map(class_names = self.class_names, path = self.map_out_path)[1]
  File "D:\python\pycharm\documentes\project\deep-learning-for-image-processing-master\object\mobilenet-yolov4-pytorch-main\utils\utils_map.py", line 910, in get_coco_map
    results_dr  = preprocess_dr(DR_PATH, class_names)
  File "D:\python\pycharm\documentes\project\deep-learning-for-image-processing-master\object\mobilenet-yolov4-pytorch-main\utils\utils_map.py", line 874, in preprocess_dr
    lines_list      = file_lines_to_list(os.path.join(dr_path, image_id))
  File "D:\python\pycharm\documentes\project\deep-learning-for-image-processing-master\object\mobilenet-yolov4-pytorch-main\utils\utils_map.py", line 145, in file_lines_to_list
    content = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 4: illegal multibyte sequence

**Comment by bubbliiiing** [comment]
中文
