### ISSUE TITLE
运行summary时出现了报错

### ISSUE THREAD

**Issue by Vision-LYF** [bubbliiiing/mobilenet-yolov4-pytorch#53]
import torch
from thop import clever_format, profile
from torchsummary import summary

from nets.yolo import YoloBody

if __name__ == "__main__":
    input_shape     = [416, 416]
    anchors_mask    = [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    num_classes     = 80
    backbone        = 'mobilenetv1'
    
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    m       = YoloBody(anchors_mask, num_classes, backbone=backbone).to(device)
    summary(m, (3, input_shape[0], input_shape[1]))
    
    # mobilenetv1-yolov4 40,952,893
    # mobilenetv2-yolov4 39,062,013
    # mobilenetv3-yolov4 39,989,933

    # 修改了panet的mobilenetv1-yolov4 12,692,029
    # 修改了panet的mobilenetv2-yolov4 10,801,149
    # 修改了panet的mobilenetv3-yolov4 11,729,069

    dummy_input     = torch.randn(1, 3, input_shape[0], input_shape[1]).to(device)
    flops, params   = profile(m.to(device), (dummy_input, ), verbose=False)
   
    flops           = flops * 2
    flops, params   = clever_format([flops, params], "%.3f")
    print('Total GFLOPS: %s' % (flops))
    print('Total params: %s' % (params))

我在运行以上程序时出现了以下错误：Traceback (most recent call last):
  File "E:\PycharmProjects\mobilenet-yolov4-pytorch-main\mobilenet-yolov4-pytorch-main\summary.py", line 8, in <module>
    from nets.yolo import YoloBody
  File "E:\PycharmProjects\mobilenet-yolov4-pytorch-main\mobilenet-yolov4-pytorch-main\nets\yolo.py", line 7, in <module>
    from .densenet import _Transition, densenet121, densenet169, densenet201
  File "E:\PycharmProjects\mobilenet-yolov4-pytorch-main\mobilenet-yolov4-pytorch-main\nets\densenet.py", line 8, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'

**Comment by bubbliiiing** [comment]
额，你改成torch.hub

**Comment by Vision-LYF** [comment]
谢谢导儿
