### ISSUE TITLE
mobilenetv1权重的由来？

### ISSUE THREAD

**Issue by myzhuang** [bubbliiiing/mobilenet-yolov4-pytorch#58]
您好！想问一下百度云里面mobilenetv1_weight.pth权重是来自于哪里？是不是基于imagenet的预训练模型？能否提供一下原先的该模型的imagenet的训练地址？拜托了。我一直在pytorch或者torchvision代码中找不到mobilenetv1的预训练pth文件，只有v2v3的，很奇怪。

**Comment by Leochen9** [comment]
Traceback (most recent call last):
  File "D:\Desktop1\deeplabv3-plus-pytorch-3.0\train.py", line 267, in <module>
    model   = DeepLab(num_classes=num_classes, backbone=backbone, downsample_factor=downsample_factor, pretrained=pretrained)
  File "D:\Desktop1\deeplabv3-plus-pytorch-3.0\nets\deeplabv3_plus.py", line 184, in __init__
    self.backbone = GhostNet(pretrained = pretrained)
  File "D:\Desktop1\deeplabv3-plus-pytorch-3.0\nets\deeplabv3_plus.py", line 71, in __init__
    model.load_state_dict(state_dict)
  File "D:\anaconda3\envs\pytorch_1\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GhostNet:
	Missing key(s) in state_dict: "stem.0.weight", "stem.1.weight", "stem.1.bias", "stem.1.running_mean", "stem.1.running_var", "features.0.primary_conv.0.weight", "features.0.primary_conv.1.weight", "features.0.primary_conv.1.bias", "features.0.primary_conv.1.running_mean", "features.0.primary_conv.1.running_var", "features.0.cheap_operation.0.weight", "features.0
导，这个问题怎么解决啊，它提示我确实一些键，但又多出一些键位
